#!/usr/bin/python3
import psycopg2
import threading
import queue
import sys
from datetime import datetime

def console(q):
    while 1:
        cmd = input('> ')
        q.put(cmd)
        if cmd == 'quit':
            break

def getUser(userID):
    try: 
        connection = psycopg2.connect("dbname='davidchaid' user='davidchaid' host='localhost'")

        cursor = connection.cursor()
        postgreSQL_select_Query = "select * from rfpidb where id = %s" % (number)

        cursor.execute(postgreSQL_select_Query, (userID,))
        mobile_records = cursor.fetchall()
        for row in mobile_records:
            print("")
            print("First_Name = ", row[1])
            print("Last_Name  = ", row[2])
            print("Email  = ", row[3])
            print("Gender  = ", row[4])
            print("Country  = ", row[5])

    finally:
        if (connection):
            cursor.close()
            connection.close()
            print("")
            print("Ticket Created \n")

while True:
    print("")
    print("Swipe badge to create ticket...")
    number = input()
    getUser(number)
